using HarmonyLib;
using System.Collections.Generic;
using System.Reflection;
using System.Linq;
using System.Reflection.Emit;
using HistoryKit;
using XRL;
using XRL.Rules;
using XRL.Annals;
using XRL.Language;
using XRL.World.Parts;
using XRL.World.WorldBuilders;

namespace zbrek_CustomWorldGeneration.HarmonyPatches
{
    [HarmonyPatch(typeof(QudHistoryFactory))]
    [HarmonyPatch(nameof(QudHistoryFactory.GenerateNewSultan))]
    public static class SultanHistoryLengthPatch
    {

        public static int GetSultanMultiplier()
        {
            return The.Game.GetIntGameState("zbrek_CustomWorldGeneration_Sultan", 1);
        }
        static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
        {
            var getMultiplier = AccessTools.Method(typeof(SultanHistoryLengthPatch), nameof(GetSultanMultiplier));
            bool patched = false;

            // I'm multiplying the length of the first loop, originally 8

            var codes = instructions.ToList();
            for (int i = 0; i < codes.Count; i++)
            {
                var code = codes[i];
                if (!patched && i + 1 < codes.Count && code.opcode == OpCodes.Ldc_I4_8 && (codes[i + 1].opcode == OpCodes.Blt || codes[i + 1].opcode == OpCodes.Blt_S))
                {
                    patched = true;
                    yield return new CodeInstruction(OpCodes.Ldc_I4_8);
                    yield return new CodeInstruction(OpCodes.Call, getMultiplier);
                    yield return new CodeInstruction(OpCodes.Mul);
                }
                else
                {
                    yield return code;
                }
            }
        }
    }


    [HarmonyPatch(typeof(JoppaWorldBuilder))]
    [HarmonyPatch(nameof(JoppaWorldBuilder.AddSultanHistoryLocations))]
    public static class SultanHistoricSitesPatch
    {
        public static int GetSultanMultiplier()
        {
            return The.Game.GetIntGameState("zbrek_CustomWorldGeneration_Sultan", 1);
        }

        [HarmonyPatch(typeof(JoppaWorldBuilder), "AddSultanHistoryLocations")]
        public static class SultanHistoryLocationDungeonPatch
        {
            public static int GetSultanMultiplier()
            {
                return The.Game.GetIntGameState("zbrek_CustomWorldGeneration_Sultan", 1);
            }

            static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
            {
                var codes = instructions.ToList();
                var getMultiplier = AccessTools.Method(typeof(SultanHistoryLocationDungeonPatch), nameof(GetSultanMultiplier));
                bool injected = false;

                // I'm modifying the value of the inner loop number that is generated by adding Stat.Random to it (OpCodes.Ldloc_S, 11).
                // I'm looking for historicEntitySnapshot.GetProperty("newName") instruction to multiply it after its value is chosen

                for (int i = 0; i < codes.Count; i++)
                {
                    var code = codes[i];
                    yield return code;

                    if (!injected
                        && code.opcode == OpCodes.Callvirt
                        && code.operand is System.Reflection.MethodInfo method
                        && method.Name == "GetProperty")
                    {
                        if (i >= 2
                            && codes[i - 2].opcode == OpCodes.Ldstr
                            && codes[i - 2].operand as string == "newName")
                        {
                            injected = true;
                            yield return new CodeInstruction(OpCodes.Ldloc_S, 11);
                            yield return new CodeInstruction(OpCodes.Call, getMultiplier);
                            yield return new CodeInstruction(OpCodes.Mul);
                            yield return new CodeInstruction(OpCodes.Stloc_S, 11);
                        }
                    }
                }
            }
        }
    }

    [HarmonyPatch(typeof(QudHistoryFactory))]
    [HarmonyPatch(nameof(QudHistoryFactory.GenerateNewSultanHistory))]

    public static class SultanHistoryRegionsPatch
    {
        public static int GetSultanMultiplier()
        {
            return The.Game.GetIntGameState("zbrek_CustomWorldGeneration_Sultan", 1);
        }

        static IEnumerable<CodeInstruction> Transpiler(IEnumerable<CodeInstruction> instructions)
        {
            var getMultiplier = AccessTools.Method(typeof(SultanHistoryRegionsPatch), nameof(GetSultanMultiplier));
            bool patched = false;

            // I'm multiplying the number of regions added in the loop

            var codes = instructions.ToList();
            for (int i = 0; i < codes.Count; i++)
            {
                var code = codes[i];

                if (!patched && code.Calls(AccessTools.Method(typeof(Stat), nameof(Stat.Random), new System.Type[] { typeof(int), typeof(int) })))
                {
                    patched = true;

                    yield return code;
                    yield return new CodeInstruction(OpCodes.Call, getMultiplier);
                    yield return new CodeInstruction(OpCodes.Mul);
                }
                else
                {
                    yield return code;
                }
            }
        }
    }
}